name: tag prod

on:
  workflow_dispatch:
    inputs:
      ref:
        description: |
          Ref to deploy, can be a commit sha or any ref
        default: "dev"
        required: true
        type: string

jobs:
  tag-prod:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.ref }}

      - name: setup git
        run: |
          git config --global user.name "good bot"
          git config --global user.email good-bot@example.com

      - name: set tag
        run: |
          git tag -f prod
          git push -f --tags

      - name: push branch
        run: |
          git push -f origin dev:prod_branch
